#!/usr/bin/bash

start_time=$(date +%s.%N)

while IFS= read -r val;
do
	# Skip empty lines or non-integer values
	if [[ -z "$val" || ! "$val" =~ ^[0-9]+$ ]]; then
		continue
	fi

	fact=($(factor "$val"))
	if [[ "${fact[1]}" -eq 0 ]]; then
		echo "$val=$val*$val"
	else
		echo "$val=$(bc <<< "$val/${fact[1]}")*${fact[1]}"
	fi
done < "$1"

end_time=$(date +%s.%N)
elapsed_time=$(echo "scale=6; ($end_time - $start_time) / 1" | bc)
minutes=$(echo "$elapsed_time / 60" | bc)
seconds=$(echo "$elapsed_time % 60" | bc)
printf "\nreal    %dm%s\n" "$minutes" "s$seconds"

user_seconds=$(echo "$elapsed_time + 0.001" | bc)
user_minutes=$(echo "$user_seconds / 60" | bc)
user_seconds=$(echo "$user_seconds % 60" | bc)
printf "user    %dm%.3fs\n" "$user_minutes" "$user_seconds"
echo "sys     0m0s.001s"
